services:
  - type: web
    name: ecom-watch
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn ecom_watch.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ecom-watch-db
          property: connectionString
databases:
  - name: ecom-watch-db
    plan: free
    